import { useState } from "react";
import styles from "../styles/Home.module.css";
import Nav from "./components/Nav";
import HomeMain from "./components/HomeMain";
import Head from "next/head";

function Home() {
  return (
    <>
      <Head>
        <title>Spring Capital</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="App">
        <HomeMain />
        <h3>Meow</h3>
      </div>
    </>
  );
}

export default Home;
